In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

np.int64(8)

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:4]

array([0, 1, 2, 3])

In [8]:
arr[0:4] = 100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[0][1]

np.int64(10)

In [22]:
arr_2d[1]

array([20, 25, 30])

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr<3]

array([1, 2])

In [36]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [41]:
arr_2d[:,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])